config/routes.rb
Rails.application.routes.draw do
  
  get 'angular/index'

  devise_for :users

  root to: 'welcome#index'

  resources :stories

  get '/angular', to: 'angular#index'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address
  include Mongoid::Document
  include Mongoid::Timestamps

  field :street_name, type: String
  field :number, type: String
  field :address_line1, type: String
  field :address_line2, type: String
  field :city, type: String
  field :state_province, type: String
  field :postal_code, type: String
  field :country, type: String
  field :latitude, type: Float
  field :longitude, type: Float

  # Cached values.

  # Note this: ids are of class ObjectId.

  # Relationships.
  belongs_to :user
  belongs_to :story

  # Validations.
end

app/models/story.rb
class Story
 include Mongoid::Document
 include Mongoid::Timestamps

 field :title,     type: String
 field :url,       type: String
 field :slug,      type: String
 field :voters,    type: Array
 field :votes,     type: Integer, :default => 0
 field :relevance, type: Integer, :default => 0

 # Cached values.
 field :comment_count, type: Integer, :default => 0
 field :username,      type: String

 # Note this: ids are of class ObjectId.

 # Relationships.
 belongs_to :user
 has_one :address

 # Validations.
 validates_presence_of :title
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  # Cached values.

  # Note this: ids are of class ObjectId.

  # Relationships.
  has_many :stories
  has_one :address

  # Validations.
  
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = current_user.stories.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = current_user.stories.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = current_user.stories.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params[:story]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/angular_helper.rb
module AngularHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_name
    "MongoidDB Test"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      "http://TBD.com"
    else
      # Our dev & test URL
      "http://localhost:3000/"
    end
  end

  def meta_author
    # Change the value below between the quotes.
    "AppCo"
  end

  def meta_description
    # Change the value below between the quotes.
    "description TBD"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "AppCo WebApp"
  end

  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/angular/index.html.erb
<div class="container-fluid">
  <div class="view-container">
    <div ng-view class="view-frame animate-view"></div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in" role="alert">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to site_name, root_path, class: "navbar-brand" %>
  </div>
  <div id="navbar" class="navbar-collapse collapse">

    <% unless user_signed_in? %><!-- No one signed in -->

      <ul class="nav navbar-nav navbar-right">
        <li><%= button_to 'Sign up', registration_path(:user), class: "btn btn-default navbar-btn" %></li>
      </ul>

      <%= form_for(:user, :url => session_path(:user), html: {class: "navbar-form navbar-right"} ) do |f| %>
        <div class="form-group">
          <%= f.text_field :email,  placeholder: "Email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
        </div>
        <%= f.submit 'Sign in', class: "btn btn-success" %>
      <% end %><!-- ./form -->

    <% else %><!-- Client signed in -->

      <ul class="nav navbar-nav">
        <li><%= link_to 'Stories', stories_path %></li>
        <li><%= link_to 'Angular', angular_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text">Signed in as <a href="#" class="navbar-link"><%= current_user.email %></a></p></li>
        <li><%= button_to 'Sign out', destroy_session_path(:user), method: :delete, class: "btn btn-default navbar-btn" %></li>
      </ul>

    <% end %>
  </div><!--/.navbar-collapse -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= site_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav_bar' %>

    <%= render partial: "layouts/flash_messages", flash: flash %> 

	<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<table class="table">
  <thead>
    <tr>
      <th>id</th>
      <th>title</th>
      <th>url</th>
      <th>slug</th>
      <th>voters</th>
      <th>votes</th>
      <th>relevance</th>
      <th>address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.id %></td>
        <td><%= story.title %></td>
        <td><%= story.url %></td>
        <td><%= story.slug %></td>
        <td><%= story.voters %></td>
        <td><%= story.votes %></td>
        <td><%= story.relevance %></td>
        <td><%= (story.address) ? story.address.address_line1 : nil %></td>

        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
<%= will_paginate @stories, renderer: BootstrapPagination::Rails %>
</p>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<div class="container">
	<% for attribute in @story.attributes.keys %>
	  <p><%= attribute.humanize %>: <%= @story.attributes[attribute].to_s %></p>
	<% end %>
</div>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/welcome/_parallax_sections.html.erb
<style type="text/css">
	.parallaxParent {
		height: 100vh;
		overflow: hidden;
	}
	.parallaxParent > * {
		height: 200%;
		position: relative;
		top: -100%;
	}
</style>

<div id="parallax1" class="parallaxParent">
	<div style="background-image: url(<%= image_url 'example_parallax_bg1.png' %>);"></div>
</div>
<div id="parallax2" class="parallaxParent">
	<div style="background-image: url(<%= image_url 'example_parallax_bg2.png' %>);"></div>
</div>
<div id="parallax3" class="parallaxParent">
	<div style="background-image: url(<%= image_url 'example_parallax_bg3.png' %>);"></div>
</div>

<script>
	// init controller
	var controller = new ScrollMagic.Controller({globalSceneOptions: {triggerHook: "onEnter", duration: "200%"}});

	// build scenes
	new ScrollMagic.Scene({triggerElement: "#parallax1"})
					.setTween("#parallax1 > div", {y: "80%", ease: Linear.easeNone})
					.addIndicators()
					.addTo(controller);

	new ScrollMagic.Scene({triggerElement: "#parallax2"})
					.setTween("#parallax2 > div", {y: "80%", ease: Linear.easeNone})
					.addIndicators()
					.addTo(controller);

	new ScrollMagic.Scene({triggerElement: "#parallax3"})
					.setTween("#parallax3 > div", {y: "80%", ease: Linear.easeNone})
					.addIndicators()
					.addTo(controller);
</script>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
		
<%= render 'welcome/parallax_sections' %>